#!/bin/sh

myname="$0"
fetchcmd=curl

args=$(getopt f $*)
if [ $? -ne 0 ]; then
	echo "Usage: $myname [-f] linktorss" >& 2
	exit 1
fi

set -- $args
while [ "$1" != -- ]; do
	case "$1" in
		-f) fetchcmd=cat ;;
	esac
	shift
done
shift

if [ "$#" -eq 1 ]; then
	$fetchcmd $1|grep "<enclosure url"|cut -d'"' -f2|mpc add
else
	echo "Usage: $myname linktorss" >&2
	exit 1
fi
